### ISSUE TITLE
Communicating to the BoD and public when LAM has events

### ISSUE THREAD

**Issue by nedventures** [LAMakerspace/ToDo#16]
How can we implement this?
@tarabrown had mentioned we make a calendar that can be public and then share it on our website.
Please advise.

**Comment by myamakerspace** [comment]
The issue here is that we aren't able to promote the library branch ones, but we still want to make the board aware of what program is happening. We can do a public calendar for the Meltdown stuff, and putting that on a public calendar on the website is easy and fine.

I believe we decided that the solution for the board's internal calendar would be a Google Site, this is where the financial dashboard and agendas --  lots of info for the board - - should live.

**Comment by myamakerspace** [comment]
We should make the google site a new issue now, and add putting a calendar page on the site to the site improvement issue.

**Comment by myamakerspace** [comment]
Then close this issue
