### ISSUE TITLE
Cross Campus DTLA - Transportation

### ISSUE THREAD

**Issue by nedventures** [LAMakerspace/ToDo#46]
1. Parking pass is $200/month for the first 6 months, then $250/month after that.
2. Check into Metro Pass

**Comment by myamakerspace** [comment]
Athena Parking, 847 W 8th, is $150 for a month, $12 per day.
So, a month would be the same cost as 12 days. 
The question is, Do we think we'd park more than 12 days a month.
Thinking out loud -- There are quite a few days where I have a meeting and it would be better if I could just drive right to work rather than go home, then get on the train.

[DTLA Daily Parking.pdf](https://github.com/LAMakerspace/ToDo/files/249534/DTLA.Daily.Parking.pdf)

**Comment by myamakerspace** [comment]
Metro Annual Employer Pass

https://www.metro.net/riding/aepp/

**Comment by myamakerspace** [comment]
Please purchase the Athena parking pass. It will save me time when i have meetings which is a lot.

**Comment by myamakerspace** [comment]
So the Metro employer pass thing you have to have a minimum of 3 ppl. :(

We can pay $100 a month for metrocard for you.

**Comment by nedventures** [comment]
Mya has credit card. When she goes to CCDTLA she will purchase.
